name: Automation tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest tests/ --headless
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4.0
        with:
          name: test_artifacts
          path: tmp/
          if-no-files-found: error
          retention-days: 30
        
